org.gradle.jvmargs=-Xmx1G

maven_group=com.skellybuilds
archive_name=servermodmenu

minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.2
fabric_version=0.133.0+1.21.8
quilt_loader_version=0.29.0-beta.3
mod_version=0.9.8.1+build.1

# Project Metadata
project_name=Server Mod Menu
project_url=https://modrinth.com/mod/servermodmenu
project_logo=https://cdn.modrinth.com/data/mdAdBC85/f0e6098c730aa0686a47f22544c52c7e894163ca.png
project_color=0xecb400
default_release_type=stable

# Modrinth Metadata
modrinth_slug=servermodmenu
modrinth_id=HYGvfYUl
modrinth_game_versions=1.21.6, 1.21.7, 1.21.8
modrinth_mod_loaders=fabric, quilt

# CurseForge Metadata
curseforge_slug=servermodmenu
curseforge_id=1083190
curseforge_game_versions=1.21.6, 1.21.7, 1.21.8, Fabric, Quilt
curseforge_required_dependencies=fabric-api
curseforge_optional_dependencies=


# Mod Loader Metadata
loader_icon=https://raw.githubusercontent.com/Prospector/images/master/fabric-quilt-tiny.png
loader_name=Fabric/Quilt

# Discord Emotes
modrinth_emote=<:modrinth:802414390510354453>
github_emote=<:github:698031289223217152>
curseforge_emote=<:curseforge:1078567270239981628>

# Webhook Options
use_project_username=false

# Changelog Options
# changelog_hide_unimportant_commits tries to hide Merge commits at the moment
changelog_hide_unimportant_commits=true
changelog_max_commit_search=200
discord_webhook_changelog_line_limit=10
