# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.0.1
group=com.maniake.servermodmenu
java_version=21
minecraft_version=1.21.8
mod_name=Server Mod Menu
mod_author=Studio Maniake
mod_id=servermodmenu
license=CC0-1.0
credits=Studio Maniake
description=A mod used for downloading mods and communicating with SCMC based servers.
modrinthID = mdAdBC85
modrinthTOKEN = INSERT_TOKEN
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=false